apiVersion: v1
kind: Namespace
metadata:
  name: wingman
---
apiVersion: v1
kind: Secret
metadata:
  namespace: wingman
  name: wingman
type: Opaque
data:
  OPENAI_API_KEY: <base64 encoded key>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: wingman
  name: wingman
  labels:
    app: wingman
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wingman
  template:
    metadata:
      labels:
        app: wingman
    spec:
      containers:
        - name: wingman
          image: <docker user>/wingman:latest
          resources: {}
          ports:
            - containerPort: 3000
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: wingman
                  key: OPENAI_API_KEY
---
kind: Service
apiVersion: v1
metadata:
  namespace: wingman
  name: wingman
  labels:
    app: wingman
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: wingman
  type: ClusterIP
