name: Electron App Build and Release

on:
  push:
    branches:
      - develop
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*' # Match any tag that looks like a version number

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - os: windows-latest
            platform: windows
          - os: ubuntu-latest
            platform: linux
          - os: macos-latest
            platform: macos
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'node' # Automatically use the latest stable version of Node.js

      - name: Install PowerShell (Linux and macOS)
        if: matrix.os != 'windows-latest'
        uses: actions/setup-powershell@v2

      - name: Execute Build Script
        shell: pwsh
        run: .\build.ps1 -BuildPlatform ${{ matrix.platform }}

      - name: Extract Version from Git Tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      # Adjusted artifact paths based on platform and tag version, using PowerShell
      - name: Define Artifact Path
        shell: pwsh
        run: |
          if ($env:matrix_platform -eq "windows") {
            echo "ARTIFACT_PATH=out/make/squirrel.windows/x64/wingman-$env:VERSION Setup.exe" >> $env:GITHUB_ENV
          } elseif ($env:matrix_platform -eq "linux") {
            echo "ARTIFACT_PATH=out/make/wingman-$env:VERSION.deb" >> $env:GITHUB_ENV
          } elseif ($env:matrix_platform -eq "macos") {
            echo "ARTIFACT_PATH=out/make/wingman-$env:VERSION-universal.dmg" >> $env:GITHUB_ENV
          }

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-${{ matrix.platform }}-${{ env.VERSION }}
          path: ${{ env.ARTIFACT_PATH }}
